query {
  xSncGraphTutor { /* Replace with your Application Namespace */
    university {
      getIncidentsForStudent(
        callerId: "62826bf03710200044e0bfc8bcbe5df1"
        last: 10
      ) {
        shortDescription
        priority
        number
      }
    }
  }
}