query {
  xSncGraphTutor { /* Replace with your Application Namespace */
    student {
      getIncident(id: "08c257b21b6c0010a26310e63e4bcb54") {
        shortDescription
        priority
        number
        caller {
          name
          email
        }
        assignedTo {
          name
          email
        }
      }
    }
  }
}