query ($studentSysId: ID!) {
  xSncGraphTutor {
    university {
      getStudent(id: $studentSysId) {
        id
        name
        email
        phone
        city
        state
        incidents {
          id
          number
          shortDescription
        }
      }
    }
  }
}
